# Generated by Django 5.2.7 on 2025-11-05 20:39

import applications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to=applications.models.get_application_cv_path)),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to=applications.models.get_application_cover_path)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
