# Generated by Django 5.2.7 on 2025-10-20 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='brand_logo',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='Elevate your future — find internships & apply in one click.', max_length=160),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_text',
            field=models.CharField(blank=True, default='Explore Our Opportunities', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_lead',
            field=models.TextField(blank=True),
        ),
    ]
