# Generated by Django 5.2.7 on 2025-10-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0002_landingpage_rename_brand_logo_sitesettings_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_lead',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cta_text',
            field=models.CharField(blank=True, default='Explore Our Opportunities', max_length=60),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_lead',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
