# Generated by Django 5.2.7 on 2025-10-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_sitesettings_cta_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='cta_text',
            field=models.CharField(blank=True, default='Explore', max_length=60),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
