# Generated by Django 5.2.7 on 2025-10-27 08:02

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email address (e.g., support@Elevate.com)', max_length=254),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number (e.g., +966 50 000 0000)', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='working_hours_heading',
            field=models.CharField(blank=True, default='Working Hours', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='working_hours_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Detailed working hours (e.g., Sunday - Thursday: 9:00 AM – 5:00 PM)'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introductory text for the contact page, displayed below the title.'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, default="Thank you for your message! We'll get back to you soon.", help_text='Message displayed after a successful form submission.'),
        ),
    ]
