# Generated by Django 5.2.7 on 2025-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_contactpage_contact_email_contactpage_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='page_heading',
            field=models.CharField(blank=True, default="We'd love to hear from you!", help_text='The main heading displayed at the top of the contact page.', max_length=255),
        ),
    ]
