# Generated by Django 5.2.7 on 2025-10-27 10:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('website', '0007_contactpage_page_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_heading', models.CharField(default='About Elevate', max_length=100)),
                ('sub_heading', models.CharField(blank=True, default='Empowering Students. Connecting Opportunities.', max_length=150)),
                ('body', wagtail.fields.StreamField([('section', 3), ('what_we_offer', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for this section (e.g., Our Mission)', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Main content for this section.', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique ID for linking (e.g., mission). Leave blank if not needed.', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('content', 1), ('section_id', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'What We Offer', 'max_length': 100, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card title (e.g., For Students)', 'max_length': 50, 'required': True}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Brief description for the card.', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 3, 'min_num': 3}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unique ID for linking (e.g., offer). Leave blank if not needed.', 'max_length': 50, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('section_title', 4), ('cards', 8), ('section_id', 9)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
