# Generated by Django 5.2.7 on 2025-11-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_education_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
