# Generated by Django 5.2.7 on 2025-11-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_education_options_remove_education_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
