# Generated by Django 5.2.7 on 2025-11-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_education_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(max_length=255),
        ),
    ]
