# Generated by Django 5.2.7 on 2025-11-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_education_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
