# Generated by Django 5.2.7 on 2025-11-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_university'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]
